// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlj__PBiTNmVe2Ueko3SyQZTMIhiyM-Zc',
    appId: '1:58815424504:web:1497c4cee1f911507e580d',
    messagingSenderId: '58815424504',
    projectId: 'floodwatch-cc081',
    authDomain: 'floodwatch-cc081.firebaseapp.com',
    storageBucket: 'floodwatch-cc081.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2CxisGqnUVuwNz9YidkpbnZIAM4w66a4',
    appId: '1:58815424504:android:213782a0cffd4c287e580d',
    messagingSenderId: '58815424504',
    projectId: 'floodwatch-cc081',
    storageBucket: 'floodwatch-cc081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGbHbqtJiYvaZRw2K8VWcLBYOWHBnIO0A',
    appId: '1:58815424504:ios:cd7ca48ec3897fbb7e580d',
    messagingSenderId: '58815424504',
    projectId: 'floodwatch-cc081',
    storageBucket: 'floodwatch-cc081.firebasestorage.app',
    iosBundleId: 'com.example.floodwatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGbHbqtJiYvaZRw2K8VWcLBYOWHBnIO0A',
    appId: '1:58815424504:ios:cd7ca48ec3897fbb7e580d',
    messagingSenderId: '58815424504',
    projectId: 'floodwatch-cc081',
    storageBucket: 'floodwatch-cc081.firebasestorage.app',
    iosBundleId: 'com.example.floodwatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlj__PBiTNmVe2Ueko3SyQZTMIhiyM-Zc',
    appId: '1:58815424504:web:4d40612a0925f3db7e580d',
    messagingSenderId: '58815424504',
    projectId: 'floodwatch-cc081',
    authDomain: 'floodwatch-cc081.firebaseapp.com',
    storageBucket: 'floodwatch-cc081.firebasestorage.app',
  );
}
